spring.config.import=optional:classpath:application-local.properties
logging.pattern.console= %highlight(%d{HH:mm:ss} [%-5level]) %c{36}.%M:%L - %m%n
spring.application.name=spring-ai-project
logging.level.com.ssafy.ai=DEBUG
logging.level[org.springframework.ai.chat.client.advisor]=debug
logging.level[org.springframework.ai.tool]=debug

# ===== Server =====
server.port=8080

# ===== DB (MySQL) =====
spring.datasource.url=jdbc:mysql://localhost:3306/ssafy_ai?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=ssafy
spring.datasource.password=ssafy
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===== MyBatis =====
mybatis.type-aliases-package=com.ssafy.ai.domain


# ===== Spring AI (OpenAI 예시) =====
ssafy.gms.api-key=YOUR_KEY_HERE
spring.ai.openai.api-key=${ssafy.gms.api-key}
spring.ai.openai.chat.options.model=gpt-4o-mini

spring.ai.openai.base-url=https://gms.ssafy.io/gmsapi/api.openai.com/v1/
spring.ai.openai.chat.completions-path=chat/completions

# API Keys for Tools
# https://home.openweathermap.org/api_keys
api.openweather.key=개인키입력

# https://app.tavily.com
api.tavily.key=개인키입력


# lang fuse 설정 시작
# Spring AI 관찰 활성화
spring.ai.chat.observations.log-prompt=true
spring.ai.chat.observations.log-completion=true

# 트레이싱 활성화
management.tracing.sampling.probability=1.0

# Langfuse 엔드포인트
management.otlp.tracing.endpoint=https://jp.cloud.langfuse.com/api/public/otel/v1/traces
# echo -n "발급받은_PUBLIC_KEY:발급받은_SECRET_KEY" | base64
management.otlp.tracing.headers.Authorization=Basic 위_인코딩_결과값
management.otlp.tracing.headers.x-langfuse-ingestion-version=4
# lang fuse 설정 종료
